name: Create Hubitat Bundles
on:
  push:
    branches:
      - palette-scenes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Holiday Release Folder
      run: |
        mkdir ./holiday-release
        cp color-tools.groovy ./holiday-release/evequefou.colortools.groovy
        cp holiday-lights.groovy ./holiday-release/evequefou.HolidayLighting.groovy
        cp bundle-manifests/holiday.txt ./holiday-release/install.txt
        cp bundle-manifests/holiday.txt ./holiday-release/update.txt
    - name: Create Palette Scenes Release Folder
      run: |
        mkdir ./palette-release
        cp color-tools.groovy ./palette-release/evequefou.colortools.groovy
        cp single-active-switch.groovy ./palette-release/evequefou.SingleActiveSwitch.groovy
        cp palette-scenes.groovy ./palette-release/evequefou.PaletteScenes.groovy
        cp palette-scene-instance.groovy ./palette-release/evequefou.PaletteSceneInstance.groovy
        cp bundle-manifests/palette.txt ./palette-release/install.txt
        cp bundle-manifests/palette.txt ./palette-release/update.txt
    - name: Create zip files
      run: |
        pushd ./holiday-release
        zip -r ../holiday-lights.zip .
        popd
        pushd ./palette-release
        zip -r ../palette-scenes.zip .
        popd
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: tag
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip"
        tag: ${{ steps.tag.outputs.new_tag }}
        commit: palette-scenes
